# This is the goshd server system-wide configuration file.
#
# The strategy used for options in the default goshd_config shipped with
# oh-my-gosh is to specify options with their default value where
# possible, but leave them commented. Uncommented options override the
# default value.

[Server]
Port = 2222
Protocol = "tcp"
MaxSessions = 10

[Logging]
LogLevel = "info"

[Authentication]
KeyStore = "~/.gosh"
LoginGraceTime = 120
PermitRootLogin = false
MaxTries = 3
